# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0cadc54752b7a1f12aadd2c9e222a5ec3612d43440ae366410a191ac52247de694c79b2d99454e07dafa8c9482b7dcd16b3f6f363f889803ed4d93e570409d1

test:
  secret_key_base: 22387321638148d1def093049a3c31899464c7f4ed454cf570c3d1f219f9de3ff618ae0a8b932ae5151c99b17b954db609db9b27650bbabf7f7e4f9e66c511ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
